// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"仪表板","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"用户管理","path":"/users","icon":"UserOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"内容管理","path":"/content","icon":"FileTextOutlined","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"文章管理","path":"/content/articles","parentId":"4","id":"5"},"6":{"name":"媒体库","path":"/content/media","parentId":"4","id":"6"},"7":{"name":"系统设置","path":"/system","icon":"SettingOutlined","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"系统配置","path":"/system/config","parentId":"7","id":"8"},"9":{"name":"操作日志","path":"/system/logs","parentId":"7","id":"9"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Users__index" */'@/pages/Users/index.tsx')),
'4': React.lazy(() => import('./EmptyRoute')),
'5': React.lazy(() => import(/* webpackChunkName: "p__Content__Articles" */'@/pages/Content/Articles.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__Content__Media" */'@/pages/Content/Media.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__System__Config" */'@/pages/System/Config.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__System__Logs" */'@/pages/System/Logs.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "t__plugin-layout__Layout" */'/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/apps/admin-system-3/src/.umi-production/plugin-layout/Layout.tsx')),
},
  };
}
