// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import UserOutlined from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/UserOutlined';
import FileTextOutlined from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import SettingOutlined from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { DashboardOutlined, UserOutlined, FileTextOutlined, SettingOutlined };
