// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
// defineApp
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// plugins
export { Provider, useModel } from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/apps/admin-system-3/src/.umi-production/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/apps/admin-system-3/src/.umi-production/plugin-request';
// plugins types.d.ts
export * from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/apps/admin-system-3/src/.umi-production/plugin-antd/types.d';
export * from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/apps/admin-system-3/src/.umi-production/plugin-layout/types.d';
export * from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/apps/admin-system-3/src/.umi-production/plugin-request/types.d';
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/node_modules/.pnpm/@umijs+renderer-react@4.6.70_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react';
export type { History, ClientLoader } from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/node_modules/.pnpm/@umijs+renderer-react@4.6.70_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/zhanghe/self/code/Front-end-Architecture/puff-monorepo/node_modules/.pnpm/umi@4.6.70_@babel+core@7.29.7_@types+node@22.20.0_@types+react@18.3.31_lightningcss@1.32.0_pr_xfsrc4ftft2bkl5livqdqrsfki/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
// react ssr
export const useServerInsertedHTML: Function = () => {};
